# DB passwords are generated by Terraform and stored in SSM Parameter Store.
# Instances read them at boot, so they never appear in the code or in user_data.
# Only [_-] as special characters: safe inside bash, SQL and INI quoting.

resource "random_password" "db_root" {
  length           = 24
  special          = true
  override_special = "_-"
  min_upper        = 1
  min_lower        = 1
  min_numeric      = 1
  min_special      = 1
}

resource "random_password" "db_app" {
  length           = 24
  special          = true
  override_special = "_-"
  min_upper        = 1
  min_lower        = 1
  min_numeric      = 1
  min_special      = 1
}

resource "aws_ssm_parameter" "db_root_password" {
  name  = "/innovatech/db/root-password"
  type  = "SecureString"
  value = random_password.db_root.result
}

resource "aws_ssm_parameter" "db_app_password" {
  name  = "/innovatech/db/app-password"
  type  = "SecureString"
  value = random_password.db_app.result
}
